<nav class="py-2 lg:py-4">
    <div class="container px-3 mx-auto xl:px-32 flex items-center justify-between">
        <div class="">
            <a class="text-3xl md:text-4xl font-semibold" href="<?= route('pages.index') ?>"><?= APP_NAME ?></a>
        </div>
        <div class="flex items-center <?= (getActiveRoute('auth.show-login') || getActiveRoute('auth.show-register')) ?  'hidden' :  'block' ?>">
            <?php if (!auth_check()) { ?>
                <a class="bg-orange-900 hover:bg-orange-800 text-white py-2 px-4 rounded text-xs md:text-sm mr-2" href="<?= route('auth.show-login') ?>">Iniciar sesion</a>
            <?php } ?>

            <button id="btnSearch" class="<?= (getActiveRoute('pages.index') || getActiveRoute('pages.search')) ?  'hidden' :  'block' ?> focus:outline-none">
                <svg class="w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                </svg>
            </button>

            <?php if (auth_check()) { ?>
                <div class="flex justify-center">
                    <div class="relative">
                        <button id="btnMenu" class="relative z-10 block rounded-md bg-white p-2 focus:outline-none focus:text-gray-600">
                            <svg class=" w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" />
                            </svg>
                        </button>


                        <div id="containerMenu" class="absolute right-0 mt-1 py-2 w-48 bg-white rounded-md shadow-xl z-20 hidden">
                            <h3 class="text-base py-3 px-2"><?= auth()->name ?></h3>
                            <hr>
                            <a href="<?= route('recipes.index') ?>" class="block px-4 py-2 text-sm capitalize hover:bg-gray-200">
                                Mis recetas
                            </a>
                            <button class="block w-full text-left px-4 py-2 text-sm text-red-700 capitalize hover:bg-gray-200" onclick="document.getElementById('form-logout').submit()">Cerrar sesion</button>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
</nav>

<form action="<?= route('auth.logout') ?>" method="POST" id="form-logout"></form>


<div id="containerSearch" class="<?= (getActiveRoute('pages.index') || getActiveRoute('pages.search')) ?  'block' :  'hidden' ?> relative w-full">
    <form action="<?= route('pages.searching') ?>" method="POST" class="container px-3 mx-auto xl:px-32 relative">
        <input type="search" id="txtSearch" name="search" placeholder="¿Qué vamos a cocinar hoy?" class="w-full border border-gray-400 h-10 px-5 pr-10 rounded-full text-sm focus:outline-none" required>
        <button type="submit" class="absolute right-7 top-0 mt-3  xl:hidden">
            <svg class="h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve" width="512px" height="512px">
                <path d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z" />
            </svg>
        </button>
    </form>
</div>


<script>
    let btnSearch = document.getElementById('btnSearch');
    let containerSearch = document.getElementById('containerSearch');
    btnSearch.addEventListener('click', () => {
        if (containerSearch.classList.contains('block')) {
            containerSearch.classList.remove('block');
            containerSearch.classList.add('hidden');
        } else {
            containerSearch.classList.remove('hidden');
            containerSearch.classList.add('block');
            document.getElementById('txtSearch').focus();
        }
    });

    let btnMenu = document.getElementById('btnMenu');
    let containerMenu = document.getElementById('containerMenu');
    if (btnMenu) {
        btnMenu.addEventListener('click', () => {
            if (containerMenu.classList.contains('block')) {
                containerMenu.classList.remove('block');
                containerMenu.classList.add('hidden');
            }
            else {
                containerMenu.classList.remove('hidden');
                containerMenu.classList.add('block');
            }
        })
    }
</script>