<?php view('layouts.header') ?>
<meta property="og:title" content="Editar receta - <?= APP_NAME ?>" />
<meta property="og:description" content="Editando receta <?= $recipe->title ?>" />
<title>Editar receta - <?= APP_NAME ?></title>
<meta name="description" content="Editando receta <?= $recipe->title ?>">
<?php view('layouts.body') ?>

<div class="flex items-center justify-between mb-3">
    <h2 class="font-bold text-xl md:text-3xl">Editar receta</h2>
</div>




<?php
print_r($recipe->photo()->url)
?>





<form id="form" class="mb-4" action="<?= route('recipes.update', $recipe->url) ?>" method="POST" enctype="multipart/form-data">
    <div class="mb-3">
        <label class="block mb-2 text-sm font-medium text-gray-700" for="title">
            Titulo
        </label>
        <input name="title" value="<?= old('title', $recipe->title) ?>" class="w-full px-3 py-2 mb-1 text-sm leading-tight text-gray-700 border <?php if (has_error('title')) echo 'border-red-500' ?> rounded shadow appearance-none focus:outline-none" id="title" type="text" required autocomplete="off" />
        <?php if (has_error('title')) { ?> <p class="text-xs text-red-500"><?= error('title') ?></p> <?php } ?>
    </div>
    <div class="mb-3">
        <label class="block mb-2 text-sm font-medium text-gray-700" for="description">
            Descripcion
        </label>
        <textarea name="description" class="w-full px-3 py-2 mb-1 text-sm leading-tight text-gray-700 border <?php if (has_error('description')) echo 'border-red-500' ?> rounded shadow appearance-none focus:outline-none" rows="3" required><?= old('description', $recipe->description) ?></textarea>
        <?php if (has_error('description')) { ?> <p class="text-xs text-red-500"><?= error('description') ?></p> <?php } ?>
    </div>
    <div class="mb-3">
        <label class="block mb-2 text-sm font-medium text-gray-700" for="ingredients">
            Ingredientes
        </label>
        <textarea name="ingredients" id="ingredients" class="shadow-lg" rows="1"><?= old('ingredients', $recipe->ingredients) ?></textarea>
        <?php if (has_error('ingredients')) { ?> <p class="text-xs text-red-500"><?= error('ingredients') ?></p> <?php } ?>
    </div>
    <div class="mb-3">
        <label class="block mb-2 text-sm font-medium text-gray-700" for="steps">
            Pasos
        </label>
        <textarea name="steps" id="steps" class="shadow-lg" rows="1"><?= old('steps', $recipe->steps) ?></textarea>
        <?php if (has_error('steps')) { ?> <p class="text-xs text-red-500"><?= error('steps') ?></p> <?php } ?>
    </div>
    <div class="mb-3">
        <label class="block mb-2 text-sm font-medium text-gray-700" for="duration">
            Duración
        </label>
        <input name="duration" value="<?= old('duration', $recipe->duration) ?>" class="w-full px-3 py-2 mb-1 text-sm leading-tight text-gray-700 border <?php if (has_error('duration')) echo 'border-red-500' ?> rounded shadow appearance-none focus:outline-none" id="duration" type="number" required min="0" autocomplete="off" />
        <?php if (has_error('duration')) { ?> <p class="text-xs text-red-500"><?= error('duration') ?></p> <?php } ?>
    </div>
    <div class="mb-3">
        <label class="block mb-2 text-sm font-medium text-gray-700" for="persons">
            Cantidad de personas
        </label>
        <input name="persons" value="<?= old('persons', $recipe->persons) ?>" class="w-full px-3 py-2 mb-1 text-sm leading-tight text-gray-700 border <?php if (has_error('persons')) echo 'border-red-500' ?> rounded shadow appearance-none focus:outline-none" id="persons" type="number" required min="0" autocomplete="off" />
        <?php if (has_error('persons')) { ?> <p class="text-xs text-red-500"><?= error('persons') ?></p> <?php } ?>
    </div>
    <div class="mb-3">
        <label class="block mb-2 text-sm font-medium text-gray-700" for="type_id">
            Tipo de receta
        </label>
        <select name="type_id" class="w-full px-3 py-2 mb-1 text-sm leading-tight text-gray-700 border <?php if (has_error('type_id')) echo 'border-danger' ?>  rounded shadow focus:outline-none bg-white">
            <option value="" selected>-- Selecciona tipo --</option>
            <?php foreach ($types as $type) { ?>
                <option value="<?= $type->id ?>" <?php if (old('type_id', $recipe->type_id) === $type->id) echo 'selected' ?>><?= $type->name ?></option>
            <?php } ?>
        </select>
        <?php if (has_error('type_id')) { ?> <p class="text-xs text-red-500"><?= error('type_id') ?></p> <?php } ?>
    </div>
    <div class="mb-3 block md:grid grid-cols-12 gap-4">
        <div class="col-span-9">
            <label class="block mb-2 text-sm font-medium text-gray-700" for="image">
                Imagen
            </label>
            <div class="flex items-center">
                <input type="text" class="w-full px-3 py-2  text-sm leading-tight text-gray-700 border <?php if (has_error('image')) echo 'border-danger' ?> rounded-l shadow appearance-none focus:outline-none duration-300" name="image" id="txtImage" value="<?= old('image', substr($recipe->photo()->url, 0, 4) == 'img/' ? asset($recipe->photo()->url) : $recipe->photo()->url) ?>" autocomplete="off" />
                <button type="button" class="bg-white hover:text-orange-800 leading-tight text-orange-900 py-2 px-4 rounded-r text-sm font-bold border  shadow" onclick="loadImage()">Comprobar</button>
            </div>
            <!-- <input type="file" class="w-full px-3 py-2 mb-1 text-sm leading-tight text-gray-700 border <?php if (has_error('image')) echo 'border-danger' ?>  rounded shadow focus:outline-none bg-white" name="image" id="image" accept="image/*" onchange="loadImage(event)"> -->
        </div>
        <div class="my-3 md:my-0 col-span-3" id="containerImagePreview">
            <div class="imagen-cuadrada rounded-lg">
                <img loading="lazy" id="imagePreview" src="<?= substr($recipe->photo()->url, 0, 4) == 'img/' ? asset($recipe->photo()->url) : $recipe->photo()->url ?>" class="rounded-lg">
            </div>
        </div>
        <?php if (has_error('image')) { ?> <p class="text-xs text-red-500"><?= error('image') ?></p> <?php } ?>
    </div>

    <button class="w-full bg-orange-900 hover:bg-orange-800 text-white py-2 px-4 rounded text-sm" type="submit">
        Actualizar
    </button>
</form>




<script src="//cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
<script>
    document.getElementById('form').addEventListener('submit', function(e) {
        let imageUrlBox = document.getElementById('txtImage');
        
        if (!(/\.(jpg|jpeg|png|webp|avif|gif|svg)$/.test(imageUrlBox.value))) {
            e.preventDefault();
            alert('La url proporcionada no es una imagen');
            setTimeout(() => {
                imageUrlBox.style.borderColor="red";
                setTimeout(() => {
                    imageUrlBox.style.borderColor="transparent";
                }, 2000);
            }, 100);
        }

    })

    const loadImage = () => {
        let imageUrlBox = document.getElementById('txtImage');

        if (!imageUrlBox.value) {
            setTimeout(() => {
                imageUrlBox.style.borderColor="red";
                setTimeout(() => {
                    imageUrlBox.style.borderColor="transparent";
                }, 2000);
            }, 100);

            return;
        }

        if (!(/\.(jpg|jpeg|png|webp|avif|gif|svg)$/.test(imageUrlBox.value))) {
            setTimeout(() => {
                imageUrlBox.style.borderColor="red";
                setTimeout(() => {
                    imageUrlBox.style.borderColor="transparent";
                }, 2000);
            }, 100);
        }

        let image = document.getElementById('imagePreview');
        image.src = imageUrlBox.value;
    }
    
    // const loadImage = (e) => {
    //     let container = document.getElementById('containerImagePreview');
    //     container.classList.contains('d-none') ? container.classList.remove('d-none') : null;

    //     let image = document.getElementById('imagePreview');
    //     image.src = URL.createObjectURL(e.target.files[0]);
    //     image.onload = () => {
    //         URL.revokeObjectURL(image.src);
    //     }
    // }
    CKEDITOR.replace('steps', {
        toolbar: [{
                name: 'clipboard',
                groups: ['clipboard', 'undo'],
                items: ['Undo', 'Redo']
            },
            {
                name: 'basicstyles',
                groups: ['basicstyles', 'cleanup'],
                items: ['Bold', 'Italic', 'RemoveFormat']
            },
            {
                name: 'paragraph',
                groups: ['list', 'indent', 'blocks', 'align', 'bidi'],
                items: ['NumberedList', 'BulletedList', 'Outdent', 'Indent']
            },
            {
                name: 'tools',
                items: ['Maximize', 'ShowBlocks']
            },
        ]
    });
    CKEDITOR.replace('ingredients', {
        toolbar: [{
                name: 'clipboard',
                groups: ['clipboard', 'undo'],
                items: ['Undo', 'Redo']
            },
            {
                name: 'paragraph',
                groups: ['list', 'indent', 'blocks', 'align', 'bidi'],
                items: ['BulletedList']
            },
            {
                name: 'tools',
                items: ['Maximize', 'ShowBlocks']
            }
        ]
    });
</script>

<?php view('layouts.footer') ?>