<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="apple-touch-icon" sizes="180x180" href="<?= asset('apple-touch-icon.png') ?>">
    <link rel="icon" type="image/png" sizes="32x32" href="<?= asset('favicon-32x32.png') ?>">
    <link rel="icon" type="image/png" sizes="16x16" href="<?= asset('favicon-16x16.png') ?>">
    <link rel="manifest" href="<?= asset('site.webmanifest') ?>">
    <meta name="theme-color" content="#7B341E">


    <!-- <meta property="og:url" content=" ?>" />
    <meta property="og:type" content="article" />
    <meta property="og:image" content="https://lh3.googleusercontent.com/NcFPWdHNWzXEih0zgkYYlfEHGuiFe_HI2Hjkm9QBLLAmH_ZjAdA-KY9o9wLDOVuMofaFhJCHuw4BSnRceZ_uZzPmqjD4WHwwHtpf6z4eWKEQPe947J2p3q1wsVr_LSWix4eTyeUKSt0cPMzrmjHYn_tZHKzZhWySwgD8ISFXRPDQoXaDyaXilzQZRC92wMRQEhydRPB6ycB70fc7nypKMYrNGuKVSC6gvn9Es6qo7hmR09HP9t2oltPGXGo1fvzwBxG1b0AytVlzoMgk4gJ066QHdiB_5ZNec1GW9EKVjgx_jyQBbikVUJQbiRuAPyv3vUJNvFyx24IFoWt7ts_ViQAPew0b6jn2XTrjxSL6gbbGLgIIc0GnjbFPQebCMZgQM_z8Uz1KbSXtB4EteQrTyS3mYxcSIDZziW5Acn17NcT9XLIZqhSO1sLzT6_XUAEkRHb9yeg27wjbM38v1Y3Ax5ZaBjfVkq1q4T25No8sBjbfm-ezBST4M_sTL1mtyzr758VIAI_qQQ6FcZ5cjrYzNDWaDFeO0BdQrOKVYsOxUlPiUNM97TiYAVbNoa7i2njHEJ9q8vAlbujOK91xlL6ffOVXUv_V8ypBiID0_inmVo4EkZV6lELkE9RqxuS1pT-5dTsOeGimG42hC9CrtVMQLuNnb-UbS1yasxGU5KvF7LEBAw5sn2b63I7aObaqB_k=s512-no?authuser=0" /> -->

    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" type="text/css" href="<?= asset('css/app.css') ?>">
